channels:
- conda-forge
dependencies:
- python=3.10.18
- pip<=25.1
- pip:
  - mlflow==2.11.3
  - cloudpickle==3.1.1
  - numpy==1.24.4
  - packaging==23.2
  - pandas==2.0.3
  - psutil==5.9.8
  - pyyaml==6.0.2
  - scikit-learn==1.3.2
  - scipy==1.10.0
  - xgboost==2.0.3
name: mlflow-env
